server:
  port: 8081

spring:
  application:
    name: weather-agent
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.8-flash
